#include <stdio.h>

/*
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms will
 * be:
 *
 *     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do
 * not exceed four million, find the sum of the even-valued terms.
 */

int sumOfEvenFibs(int ceiling)
{
    int runningTotal = 0;
    int back1 = 1;
    int back2 = 0;

    for (int i = 0; i <= ceiling; i++)
    {
        if (i == back1 + back2)
        {
            back2 = back1;
            back1 = i;
            if (i % 2 == 0)
            {
                runningTotal += i;
            }
        }
    }

    return runningTotal;
}

int main(int argc, char *argv[])
{
    printf("Answer: %d\n", sumOfEvenFibs(4000000));
    return 0;
}
