#!/usr/bin/env python

# PROBLEM 2
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will
# be:
# 
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

def fib(x):
    fib = []
    back1 = 1
    back2 = 0

    for i in range(0, x):
        if i == back1 + back2:
            fib.append(i)
            back2 = back1
            back1 = i
    return fib

sum = 0
fibSequence = fib(4000000)
for i in range(0, len(fibSequence)):
    if fibSequence[i] % 2 == 0:
        sum += fibSequence[i]

print "Sum: %d" % sum
