#!/usr/bin/perl
use warnings;
use strict;
use List::Util qw(sum);

# PROBLEM 2
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will
# be:
# 
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

my $sum = sum(grep { $_ % 2 == 0 } &calculateFibonacci(4000000));
print("Sum: $sum\n");

sub calculateFibonacci()
{
    my @fib;
    my $back1 = 1;
    my $back2 = 0;

    for (my $i = 0; $i < $_[0]; $i++)
    {
        if ($i == ($back1 + $back2))
        {
            push(@fib, $i);
            $back2 = $back1;
            $back1 = $i;
        }
    }

    return @fib;
}
